### ISSUE TITLE
Missed Appointment and Appointment and attrition Report Query

### ISSUE THREAD

**Issue by VictorOwinoKe** [palladiumkenya/kenyahmis-releases#2]
1. Error 1: We can not have a zero missed appointment.
This attachment  describes what I am saying. 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/56676033/210044519-86473678-e2a6-4526-9c77-363319a080c1.png">
2. People with Future appointments can not be in the missed appointment list. 
Kindly check the script to see what could be the error.
<img width="425" alt="image" src="https://user-images.githubusercontent.com/56676033/210044963-de7107ff-fafc-4875-9de7-d8472a0056b6.png">
3. Missed Appointment Appointment and attrition Report does not give the same number of clients client who missed between any two given dates.

**Comment by Lavatsaleo** [comment]
This was fixed in the latest release
